version: '2'
services:
  app:
    image: node:8.9
    command: bash -c "yarn && yarn dev"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 3000:3000
    depends_on:
      - es
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
